version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ttyyuu11..
      MYSQL_ROOT_HOST: "%" 
      MYSQL_DATABASE: farmazon
    ports:
      - "3307:3306"
    volumes:
      # - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
      # the first on will be relative to the file
      - ./sql/01-seed.sql:/docker-entrypoint-initdb.d/01-seed.sql
      - ./sql/02-mockData.sql:/docker-entrypoint-initdb.d/02-mockData.sql



