version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ttyyuu11..
      MYSQL_ROOT_HOST: "%" 
    ports:
      - "3307:3306"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql


